# Generated by Django 4.0 on 2022-01-16 12:06

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', ckeditor.fields.RichTextField()),
                ('product_photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('product_photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('product_photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('product_photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('product_photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
