# Generated by Django 4.0 on 2022-02-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_material',
            field=models.BooleanField(default=False),
        ),
    ]
