# Generated by Django 4.0 on 2022-02-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_is_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_medicine',
            field=models.BooleanField(default=False),
        ),
    ]
