# Generated by Django 4.0.1 on 2022-01-20 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hamro', '0002_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
