# Generated by Django 4.0 on 2022-02-02 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hamro', '0007_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_photo1', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('banner_photo2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('banner_photo3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('banner_photo4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('banner_photo5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('banner_photo6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
