# Generated by Django 4.0 on 2022-02-02 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hamro', '0008_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_photo1', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('brand_photo2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('brand_photo3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('brand_photo4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('brand_photo5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('brand_photo6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
