# Generated by Django 4.0 on 2022-02-02 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hamro', '0009_brand_delete_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='brand_photo1',
            new_name='brand_photo_1',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='brand_photo2',
            new_name='brand_photo_2',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='brand_photo3',
            new_name='brand_photo_3',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='brand_photo4',
            new_name='brand_photo_4',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='brand_photo5',
            new_name='brand_photo_5',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='brand_photo6',
            new_name='brand_photo_6',
        ),
    ]
